### ISSUE TITLE
Errors replacing URLs

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/scribe2#3]
A few times lately I've been unable to tidy some parts of minutes on the fly using scribe.perl on W3C IRC,  using this repo's code, according to the generated link:

> Minutes manually created (not a transcript), formatted by [scribe.perl](https://w3c.github.io/scribe2/scribedoc.html) version 117 (Tue Apr 28 12:46:31 2020 UTC). 

I think this may have something to do with the code that is using `/` and `|` as delimiters to the `s` command, but I'm speculating. It usually has difficulty with URLs. My suspicion is it is using either delimiter throughout, instead of the previous behaviour where the delimiter immediately after the `s` was the only one that would work later in the line as a delimiter.

Example segment from an IRC log:

```irc
16:12:27 [atsushi]
    https://github.com/w3c/imsc/settings/branches
16:15:20 [nigel]
    rrsagent, make minutes v2
16:15:20 [RRSAgent]
    I have made the request to generate https://www.w3.org/2020/06/04-tt-minutes.html nigel
16:19:34 [nigel]
    s|https://‌github.com/‌w3c/‌imsc/‌settings/‌branches||
16:19:37 [nigel]
    rrsagent, make minutes v2
```

results in an output like:

> &lt;atsushi&gt; https://‌github.com/‌w3c/‌imsc/‌settings/‌branches
> &lt;nigel&gt; s|https://‌‌github.com/‌‌w3c/‌‌imsc/‌‌settings/‌‌branches||

with embedded diagnostics:

> Failed: s|https://‌github.com/‌w3c/‌imsc/‌settings/‌branches||

Some other test cases:

```irc
16:24:23 [nigel]
    s|https:||
16:25:21 [nigel]
    s/s|h/h
16:25:32 [nigel]
    s/s||/s
16:26:59 [nigel]
    s|github-bot, end topic||
16:27:00 [nigel]
    rrsagent, make minutes v2
16:27:00 [RRSAgent]
    I have made the request to generate https://www.w3.org/2020/06/04-tt-minutes.html nigel
```

results in this in the diagnostics:

> Succeeded: s|https:||
>
> Failed: s/s|h/h
>
> Failed: s/s||/s
>
> Succeeded: s|github-bot, end topic||

**Comment by bert-github** [comment]
The reason the s/// command failed is that it contains some invisible
characters. The URL you wanted to replace was

    https://github.com/w3c...

but the s/// command actually contains

    https://&#8204;github.com/&#8204;w3c...

The &#8204 is Unicode character U+200C, ZERO WIDTH NON-JOINER.

What I think happened is that you copy-pasted the URL not from the IRC
log but from the generated HTML minutes. In those minutes, all URLs are,
by default, modified to indicate places where the URL may be broken at
the end of a line (because many browsers do not automatically break
words after slashes.)

There is an option to stop URLs from being modified,

    scribeoptions: -url=full

(The full option is --urlDisplay=full, but it can be abbreviated.)

Do we need to add something else to avoid this problem?



Bert
-- 
  Bert Bos                                ( W 3 C ) http://www.w3.org/
  http://www.w3.org/people/bos                               W3C/ERCIM
  bert@w3.org                             2004 Rt des Lucioles / BP 93
  +33 (0)4 92 38 76 92            06902 Sophia Antipolis Cedex, France

**Comment by nigelmegitt** [comment]
Gosh, that's a surprise, thanks for spotting it @bert-github . I never knew URLs were deliberately mangled and did not expect it. I've never noticed that scribe option either. 

Moving on from my puzzlement about why the invisible character is being inserted, if scribe.perl is _inserting_ those characters then it probably ought to ignore them when string matching, since for the user, it is effectively impossible to see if they are there or not, without going via a hex editor or something similar.

**Comment by bert-github** [comment]
OK, I made the s/// command strip the invisible characters.

**Comment by nigelmegitt** [comment]
Thanks, sounds good, and the commits look reasonable on a quick eyeball scan. I'll test it out on Thursday, assuming this is deployed by then.

**Comment by bert-github** [comment]
It should be available in RRSAgent now. (With thanks to Ralph!)
